# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
    ]
