# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180404_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
