# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_banner_is_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_banner',
        ),
    ]
